### ISSUE TITLE
Modularize Tokenizer & Parser

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#19]
# Code Refactoring: Modularize Tokenizer and Parser

## Overview
Improve the maintainability of the tokenizer and parser components by breaking down monolithic files into more modular, focused modules.

## Description
The current implementation of `tokenizer.c` and `parser.c` contains multiple responsibilities within single files. This refactoring aims to:
- Separate concerns
- Improve code readability
- Enhance maintainability
- Facilitate easier testing

### Tokenizer Restructure
``` bash
tokenizer/
├── tokenizer.c
├── tokenizer.h
├── keywords.c
├── keywords.h
├── token_utils.c
└── token_utils.h
```

### Parser Restructure
```bash
parser/
├── parser.c
├── parser.h
├── ast_node_utils.c
├── ast_node_utils.h
├── parse_statements.c
├── parse_statements.h
└── parse_expressions.c
└── parse_expressions.h
```

## Tasks/Deliverables
- [x] Create `keywords.h` and `keywords.c`
  - [x] Move keyword and operator arrays
  - [x] Implement keyword/operator validation functions

- [x] Create `token_utils.h` and `token_utils.c`
  - [x] Add utility functions for token operations
  - [x] Implement error handling utilities

- [x] Refactor `tokenizer.c`
  - [x] Separate core tokenization logic
  - [x] Use new utility functions
  - [x] Improve error handling
- [x] Create `ast_node_utils.h` and `ast_node_utils.c`
  - [x] Implement node creation and memory management functions
  - [x] Add helper functions for different node types

- [x] Refactor `parser.c`
  - [x] Distribute parsing logic across new files
  - [x] Improve AST node creation and management
  - [x] Enhance error reporting

## Acceptance Criteria
- [x] All existing functionality remains unchanged
- [x] Code coverage maintained or improved
- [x] Reduced cyclomatic complexity
- [x] Improved readability and modularity
- [x] All existing tests pass

## Potential Challenges
- Managing dependencies between new modules
- Ensuring minimal performance overhead
- Maintaining clean and consistent error handling

## Additional Notes
- Carefully manage header inclusions
- Use forward declarations to minimize dependencies
- Consider creating a common error handling mechanism
