### ISSUE TITLE
Implement `debug_print` Wrapper for Conditional Debugging in Interpreter

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#27]
# Implement `debug_print` Wrapper for Conditional Debugging in Interpreter

## Description

As part of the development of the FlavorLang interpreter, I’m currently using `printf` frequently for logging debug messages in the format [DEBUG] <message>. This process has become repetitive and needs to be streamlined. I'd like to create a wrapper function for logging debug messages that will only activate when the `--debug flag` is passed via the command line.

The wrapper should allow for cleaner code and conditional debug output based on the presence of the `--debug` flag. If `--debug` is provided when running the interpreter, debug statements should be printed. Otherwise, the debug output should be suppressed.

## Acceptance Criteria
- [x] Create a `debug_print` function that wraps the `printf` functionality.
- [x] The function should take a message as input and print it in the format `[DEBUG] <message>`.
- [x] The debug output should only be printed when the `--debug` flag is passed during interpreter execution (e.g., `./flavor test.flv --debug`).
- [x] If `--debug` is not passed, no debug messages should be logged.
- [x] The `--debug` flag should be parsed by the interpreter at startup.
- [x] Ensure that the wrapper is reusable and can be called in various parts of the interpreter code without redundant checks.
- [x] Consider using a global flag or configuration object to manage the debug state.

## Additional Context
- The function should ideally support logging multiple types of messages, such as strings, variables, and data structures.
- The flag parsing logic should be implemented early in the interpreter initialization.
- For performance reasons, ensure the debug print logic has minimal impact on the runtime if debugging is disabled.
- The debug messages should have the format `[DEBUG] <timestamp> <message>`, where the timestamp is optional based on the implementation.

### Command to run the interpreter with debug output
`./flavor test.flv --debug`

### Expected output when running with the --debug flag
`[DEBUG 12:34:56] This is a test debug message`

### When --debug is not passed
`(no debug output)`

## Tasks

- [x] Implement the `debug_print` function.
- [x] Add logic to parse the `--debug` flag at interpreter startup.
- [x] Conditionally execute the debugPrint function based on the `--debug` flag.
- [x] Test that debug messages are shown when the flag is passed and suppressed otherwise.
- [x] Document the new flag and debug functionality in the project’s README or relevant documentation.
- [x] Ensure minimal performance impact when debugging is disabled.
