### ISSUE TITLE
Support for Retrieving String Inputs from the User (`taste` Statements)

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#41]
# Support for Retrieving String Inputs from the User (`taste` Statements)

## Description

Add functionality to the parser and interpreter of FlavorLang to enable retrieving string inputs directly from the user. This feature will allow users to be prompted for input during program execution, enhancing interactivity.

## Requirements
1. Syntax Support:
	- Introduce a mechanism for user input (i.e., the `taste` keyword)
	- The parser should recognize the `taste` keyword and generate the appropriate abstract syntax tree (AST) node.
2. Interpreter Behavior:
	- During execution, the interpreter should:
		1. Display the prompt provided by the `scran` keyword.
		2. Wait for the user to input a value.
		3. Assign the input value to the corresponding variable or use it directly in expressions.
3. Error Handling:
	- Handle cases where input cannot be retrieved (e.g., `EOF` or memory allocation errors).
	- Provide user-friendly error messages.

## Example

`test.flv`
```
scran "What's your favorite dessert?";
let favorite = taste;

scran "You chose:", favorite;
```

### Expected Output:
```
What's your favorite dessert?
cake
You chose: cake
```

## Implementation Details
1. Parser:
	- Update the grammar to recognize the taste keyword.
	- Extend the `ASTNode` structure to include support for a new enum `AST_INPUT` or similar.
2. Interpreter:
	- Implement logic to evaluate the `taste` keyword.
	- Use dynamic memory allocation to handle user input of unknown length (e.g., via getchar or a similar mechanism).
	- Ensure the input value is properly assigned to the specified variable.
3. Error Handling:
	- Provide meaningful error messages for invalid or failed input scenarios.
	- Ensure robust memory management to avoid leaks or crashes.

## Tasks

- [x] 1. Update the parser to recognize the `taste` keyword and prompt appropriately.
- [x] 2. Extend the AST to include `AST_INPUT` for handling `taste`.
- [x] 3. Implement input-handling logic in the interpreter.
- [x] 4. Write unit tests to verify:
	- [x] Parsing of taste.
	- [x] Correct interpretation of user input.
	- [x] Handling of edge cases (e.g., empty input, invalid input).
- [x] 5. Document the feature in the FlavorLang language guide.

## Additional Notes
- Consider edge cases such as empty or excessively large inputs.
- Ensure compatibility with existing language features, such as scran for output.
