### ISSUE TITLE
Implement the `burn` (Raise Error) Keyword

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#44]
# Implement the `burn` (Raise Error) Keyword

## Description 
The `burn` keyword is a critical addition to FlavorLang's syntax, acting as an immediate execution halter. Akin to the concept of "raising an error", it ensures the program stops running and outputs a specified message when invoked.

## Use Case
In scenarios where a program encounters an unrecoverable situation, developers can use `burn` to:

- Terminate execution instantly.
- Communicate errors clearly to the user or developer.

### Example Syntax
```
burn "Critical failure: Ingredients are missing!";
```

## Expected Behavior

- **Effect**: Halts program execution immediately upon invocation.
- **Output**: Displays the provided message in the console or error log.

## Implementation Steps

- [x] 1. Grammar Update

	- [x] Add the `burn` keyword to the FlavorLang grammar in the tokenizer and parser.

- [x] 2. Runtime Logic

	- [x] Implement the execution handler to stop program flow and display the message.

- [x] 3. Integration

	- [x] Ensure compatibility with existing features such as the debugging flag (`--debug`) for enhanced error tracing.

- [x] 4. Testing

	- [x] Verify correct behavior in cases like:
        - Standard usage (`burn` with a string).
        - Nested scenarios (inside conditionals, lops, etc.).

- [x] 5. Documentation

	- [x] Update the `README.md` and examples to reflect the new keyword, including its syntax and functionality.

## Future Considerations
- Error Handling: Ensure compatibility with `try` and `crumbs`.
- Debugging: Provide detailed tracebacks in debug mode for easier debugging.
- Nested scenarios (inside `prep`, loops, or `try`-`crumbs` blocks).
