### ISSUE TITLE
Amend Git Clone Command in Quick Start Section of README

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#45]
# Amend Git Clone Command in Quick Start Section of README

## 📝 Description  
The "Quick Start" section in the README contains an incorrect `git clone` command. It currently points to a placeholder repository URL instead of the actual FlavorLang repository under my GitHub username.

---

## Current Behavior  
The following command is used in the `README.md` under "Install the Compiler":

```bash
git clone https://github.com/your-repo/FlavorLang.git
```

Attempting to use this command results in an error as your-repo is not a valid repository.

## Expected Behavior

The command should clone the correct repository.
It should be updated to:
```
git clone https://github.com/KennyOliver/FlavorLang.git
```

## Proposed Fix

1. Update the "Quick Start" section under "Install the Compiler" to reflect the correct repository URL.
2. Verify the change renders properly in markdown and does not break any formatting.
3. Double-check that all references to the placeholder URL are replaced throughout the `README.md` (if this is ends up being applicable).

## Tasks

- [ ] Replace the git clone command in the "Quick Start" section.
- [ ] Search for other instances of your-repo in the documentation.
- [ ] Test the updated command to ensure it works as intended.
