### ISSUE TITLE
Numerous Places in README Need Updating

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#54]
# Numerous Places in README Need Updating

## Tasks
- [x] Some bits of code should be enclosed in backticks
- [x] Terminal commands should start with `$`
- [x] Some outdated wordings, code references (e.g., the `--chef` flag instead of the `--debug` flag), etc.
- [x] Indentation of some code snippet blocks is too much
- [x] Bolding not used consistently in some sections
- [x] Some sections are very outdated (e.g., Parser, Interpreter)

## Related Issues
#44 #53
