### ISSUE TITLE
Improve Debugger Output

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#58]
# Improve Debugger Output for FlavorLang

## Overview
The current debugger output for FlavorLang lacks clarity and readability. It also includes redundant timestamp information and inconsistent formatting. I'd like to propose a refined format for debug messages to enhance the developer experience.

---

### New Debug Message Format
Switch to the following debug message format:

`[DEBUG <process>] <message>`

- `<process>`:
  - `TKN`: Tokenizer
  - `PRS`: Parser
  - `RUN`: Interpreter (alternative to `INT`, open to feedback)
- `<message>`: The debug information provided by the relevant process.

### Message Coloring
To improve visibility:
- `[DEBUG <process>]`: Orange
- `<process>` (e.g., `TKN`, `PRS`, `RUN`): Green
- `<message>`: Default text color for readability.

### `debug_print` Updates
- Stop appending a newline to the provided string argument unless explicitly included.

---

## Example Output

Using the example script `test9.flv`:

### Input
```flv
let dessert = "cake";

check dessert:
    is "cake":
        show "Bake the cake!";
    is "pie":
    is "cookie":
        show "Prepare the oven!";
        break;
    else:
        show "Dessert not on the menu.";
```

### Output
```
[DEBUG TKN] Tokenization complete.
[DEBUG PRS] Starting to parse block.
[DEBUG PRS] Parsing token in block: type=0, lexeme=show
...
[DEBUG RUN] `interpret()` called.
[DEBUG RUN] Matched: `AST_ASSIGNMENT`.
[DEBUG RUN] Created new variable `dessert` with value `cake`.
...
[DEBUG RUN] `interpret_print()`
...
Bake the cake!
Dessert not on the menu.
```

## Benefits

- Improved readability with a cleaner, more structured format.
- Clear differentiation of debug messages by process using abbreviations and color.
- Flexible debug_print function for custom formatting.

## Tasks

- [x] Update debug message format across all components of FlavorLang.
- [x] Implement coloring for debug messages using ANSI escape codes.
- [x] Refactor `debug_print` to no longer automatically append `\n`.
- [x] Update documentation to reflect the new debug output style.
