### ISSUE TITLE
Add Support for Defining and Calling Functions

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#60]
# Add Support for Defining and Calling Functions

## Description
I'm now planning to add support for defining and calling functions in FlavorLang.

This feature should allow for the following:

- **Defining a function** with parameters.
- **Executing code** based on function input.
- **Early termination of function execution** using a command like `burn`.
- **Calling a function** and capturing its return value.

## Example Syntax
```
create bake_cake(temperature):
    if temperature < 180:
        show "Temperature is too low to bake!";
        burn "Cake burned!";  # Stops function execution immediately
    else:
        show "Baking cake at", temperature, "degrees!";
        deliver "Cake is ready!";

let result = bake_cake(200);
show result;
```

## Expected Behavior

- When `bake_cake` is called with a `temperature`:
    - If the temperature is below `180`, it shows a message indicating the temperature is too low and stops execution with the burn command.
    - Otherwise, it shows the message for baking and then `deliver`s the result when the cake is ready.
- The result of the function should be captured in `result` and displayed with `show result`.

## Task Breakdown

- [x] Implement function declaration syntax.
- [x] Implement function execution with parameters.
- [x] Add support for returning values from functions.
- [x] Update the parser & interpreter to recognize and handle function calls.
