### ISSUE TITLE
Create `interpreter_error` Wrapper Function to Reduce Boilerplate in Interpreter's Error Handling

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#98]
# Create `interpreter_error` Wrapper Function to Reduce Boilerplate in Interpreter's Error Handling

## Description

Currently, the interpreter contains repeated boilerplate code for error reporting, like the following pattern:
```c
fprintf(stderr, "Error: Start expression in `for` loop must be numeric\n");
exit(1);
```

To improve maintainability and reduce duplication, I propose creating a `interpreter_error` helper function that consolidates this logic.

## Proposed Solution

Create a function `interpreter_error` with the following prototype:
```c
void interpreter_error(const char *message);
```

This function would handle:
- Printing the error message to `stderr`.
- Exiting the program with a non-zero status code.

## Example implementation
```c
#include <stdio.h>
#include <stdlib.h>

void interpreter_error(const char *message) {
    fprintf(stderr, "Error: %s\n", message);
    exit(1);
}
```

## Example Usage

Replace instances like this:
```c
fprintf(stderr, "Error: Start expression in `for` loop must be numeric\n");
exit(1);
```

With this:
```c
interpreter_error("Start expression in `for` loop must be numeric");
```

## Benefits
- **Readability**: Reduces clutter and makes the error handling more concise.
- **Consistency**: Ensures all error messages follow the same format.
- **Maintainability**: Centralizes logic, making future modifications easier.

## Tasks
- [ ] Implement `interpreter_error` into `interpreter.c`.
- [ ] Refactor existing error handling code to use `interpreter_error`.
- [ ] Test to confirm error messages are consistent and the program exits as expected.
